// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbClDMLOFTS63Ftjt2-gUbpVg2S37opLk',
    appId: '1:41745264423:web:936aa612684564bd20c302',
    messagingSenderId: '41745264423',
    projectId: 'polyinside',
    authDomain: 'polyinside.firebaseapp.com',
    storageBucket: 'polyinside.appspot.com',
    measurementId: 'G-B6PP7HM52Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbqbs0IyxtB3q_tJ9kB-kk8_RxB9iRpLI',
    appId: '1:41745264423:android:428e57a3c2ecb37020c302',
    messagingSenderId: '41745264423',
    projectId: 'polyinside',
    storageBucket: 'polyinside.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJIS49i4Gif1DNYLprkekXgWx3dHcRNGU',
    appId: '1:41745264423:ios:ecc5e83ba695c81e20c302',
    messagingSenderId: '41745264423',
    projectId: 'polyinside',
    storageBucket: 'polyinside.appspot.com',
    iosBundleId: 'com.example.polyInside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJIS49i4Gif1DNYLprkekXgWx3dHcRNGU',
    appId: '1:41745264423:ios:ecc5e83ba695c81e20c302',
    messagingSenderId: '41745264423',
    projectId: 'polyinside',
    storageBucket: 'polyinside.appspot.com',
    iosBundleId: 'com.example.polyInside',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbClDMLOFTS63Ftjt2-gUbpVg2S37opLk',
    appId: '1:41745264423:web:61626b849497fc4120c302',
    messagingSenderId: '41745264423',
    projectId: 'polyinside',
    authDomain: 'polyinside.firebaseapp.com',
    storageBucket: 'polyinside.appspot.com',
    measurementId: 'G-CTES7PSRBG',
  );
}
